//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSE_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification1
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Decription { get; set; }
        public string Status { get; set; }
        public string Url { get; set; }
        public System.DateTime CreatedByDate { get; set; }
    }
}
