//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSE_BACKEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int ID { get; set; }
        public string ContactPerson { get; set; }
        public string OrganizationName { get; set; }
        public string Image { get; set; }
        public string OrganizationProgrames { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Link { get; set; }
        public string Purpose { get; set; }
        public string LinkFile { get; set; }
        public int IDState { get; set; }
    }
}
